language: php

php:
  - '5.6'
  - '7.0'

addons:
  postgresql: "9.3"

before_script:
  - psql -U postgres -c "CREATE ROLE grnrbt_censored_test LOGIN PASSWORD 'pass';";
  - psql -U postgres -c "CREATE DATABASE grnrbt_censored_test WITH OWNER grnrbt_censored_test ENCODING 'UTF8';";

script:
  - composer install
  - vendor/bin/codecept run

notifications:
  email: false